name: SonarQube Analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

    - name: Install reportgenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Run SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"UserPanel" \
          /d:sonar.host.url="http://localhost:9000" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

        dotnet build

        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
