name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master ]

jobs:
  sast:
    name: Static Code Analysis (SAST) with SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

  build:
    name: Build and Deploy App
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build app
        run: |
          echo "🔧 Run your build here (npm install, dotnet build, etc)"
          # Example for Node.js:
          # npm install
          # npm run build

      - name: Deploy to Docker (Localhost for testing)
        run: |
          echo "🐳 Building Docker image and running container"
          docker build -t insecure-app .
          docker run -d -p 8080:80 --name test-app insecure-app

  dast:
    name: DAST Scan with OWASP ZAP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for App to be ready (e.g., on localhost:8080)
        run: |
          echo "⏳ Waiting for the app to be ready..."
          sleep 20

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:8080'
          fail_action: false
          docker_name: 'owasp/zap2docker-stable'
